language: php

sudo: false

addons:
  apt:
    packages:
      - tidy

php:
  - 7.0

before_install:
  - pip install --user codecov

env:
  global:
    - DB=MYSQL CORE_RELEASE=3.4

    # Turn coverage off by default, as it's expensive time wise
    - COVERAGE=0

    # The path of the module when installed by composer
    - MODULE_PATH=websites-monitor

    # codecov token
    #- CODECOV_TOKEN=2d9e2745-63fd-46dc-a5eb-5ae7d29bb135

matrix:
  include:
      - php: 5.6
        env: DB=MYSQL COVERAGE=1
      - php: 5.6
        env: DB=SQLITE
      - php: hhvm
        env: DB=MYSQL
  allow_failures:
      - php: 5.6
        env: DB=MYSQL CORE_RELEASE=4.0
      - php: 7.0
        env: DB=MYSQL CORE_RELEASE=4.0
      - php: 5.6
        env: DB=PGSQL


before_script:
  - phpenv rehash
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

#Execute tests with or without coverage
script:
  # Execute tests with no coverage.  This is the fastest option
  - "if [ \"$COVERAGE\" = \"0\" ]; then vendor/bin/phpunit $MODULE_PATH/tests/; fi"

  # Execute tests with coverage.  Do this for a small
#  - "if [ \"$COVERAGE\" = \"1\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/; fi"

#Upload coverage even if there is a failure
after_script:
#  - "if [ \"$COVERAGE\" = \"1\" ]; then mv coverage.clover ~/build/$TRAVIS_REPO_SLUG/; fi"
#  - cd ~/build/$TRAVIS_REPO_SLUG
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - "if [ \"$COVERAGE\" = \"1\" ]; then bash <(curl -s https://codecov.io/bash) -t 2d9e2745-63fd-46dc-a5eb-5ae7d29bb135 && travis_retry php ocular.phar code-coverage:upload --format=php-clover --access-token='d0cb5cb06d4d296fe4d849c2bd5008934cbf8afe5d256ef146df32d935a783a6' coverage.clover; fi"